import { NextProviderUI } from "@/context/NextUIProvider";
import "./globals.css";

export const metadata = {
  title: "MuseoMatic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextProviderUI>{children}</NextProviderUI>
      </body>
    </html>
  );
}
