export const cityList = [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Ibagué",
    "Manizales",
    "Neiva",
    "Pereira",
    "Santa Marta",
    "Soledad",
    "Sincelejo",
    "Itagüí",
    "Valledupar",
    "Armenia",
    "Bucaramanga",
    "Villavicencio",
    "Pasto",
    "Popayán",
    "Soledad",
    "Ibagué",
    "Sincelejo",
    "Armenia",
    "Bucaramanga",
    "Villavicencio",
    "Pasto",
    "Popayán"
];

export const typesEvents = [
    "Exposiciones temporales",
    "Exposiciones permanentes",
    "Visitas guiadas",
    "Talleres",
    "Conciertos",
    "Obras de teatro",
    "Proyecciones audiovisuales",
    "Charlas",
    "Conferencias",
    "Presentaciones de libros",
    "Eventos para niños",
    "Eventos familiares",
    "Festivales",
    "Ciclos de cine",
    "Actividades educativas",
    "Visitas nocturnas",
    "Días de entrada gratuita",
    "Concursos",
    "Lanzamientos de productos",
    "Inauguraciones",
    "Mesas redondas",
    "Simposios",
    "Congresos",
    "Eventos gastronómicos",
    "Eventos literarios",
    "Eventos de bienestar",
    "Eventos inclusivos",
    "Eventos virtuales",
];

export const typesCollection = [
    "Arte",
    "Historia",
    "Ciencias Naturales",
    "Antropología",
    "Arqueología",
    "Etnografía",
    "Fotografía",
    "Arquitectura",
    "Artes Decorativas",
    "Artes Visuales",
    "Botánica",
    "Geología",
    "Zoología",
    "Mineralogía",
    "Paleontología",
    "Religión",
    "Filatelia",
    "Numismática",
    "Herbario",
    "Insectario",
    "Ornitario",
    "Entomología",
    "Hidrobiología",
    "Ictiología",
    "Lacustrología",
    "Malacología",
    "Micología",
    "Myrmecología",
    "Nematología",
    "Odonatología",
    "Pentatomología",
    "Quelonología",
    "Rinología",
    "Serpentología",
    "Tetrapodología",
    "Urodeología",
    "Vespertiliología",
    "Xilofagia",
    "Árboles",
    "Flora",
    "Fauna",
    "Minerales",
    "Fósiles",
    "Ecoetología",
    "Conservación",
    "Investigación",
    "Educación",
    "Exposiciones Temporales",
    "Eventos Especiales",
];